# Generated by Django 5.2.8 on 2025-11-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('image_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('component_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblytype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assembly_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblytype')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operator')),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=1)),
                ('assembly_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblytype')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.component')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to='api.operator')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operator')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operatorrole')),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='operators', through='api.OperatorRoleAssignment', through_fields=('operator', 'role'), to='api.operatorrole'),
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assembly_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblyexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblystep')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('BREAK_START', 'Break started'), ('BREAK_END', 'Break ended'), ('REPAIR_START', 'Repair started'), ('REPAIR_END', 'Repair ended'), ('WAIT_START', 'Waiting for material started'), ('WAIT_END', 'Waiting for material ended')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assembly_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assemblyexecution')),
                ('related_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bin')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operator')),
                ('step_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stepexecution')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('error_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.errortype')),
                ('step_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stepexecution')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StepObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=20)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('z_index', models.IntegerField()),
                ('text_content', models.TextField(blank=True)),
                ('image_path', models.CharField(blank=True, max_length=200)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblystep')),
            ],
        ),
        migrations.CreateModel(
            name='StepRequiredComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bin')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.component')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblystep')),
            ],
            options={
                'verbose_name': 'Required component for step',
                'verbose_name_plural': 'Required components for step',
            },
        ),
        migrations.AddConstraint(
            model_name='assemblystep',
            constraint=models.UniqueConstraint(fields=('assembly', 'order'), name='unique_step_order_per_assembly'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorroleassignment',
            unique_together={('operator', 'role')},
        ),
    ]
