# Generated by Django 5.2.8 on 2025-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_operator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepobject',
            name='font_size',
            field=models.IntegerField(default=40),
        ),
    ]
