# Generated by Django 5.2.8 on 2025-12-31 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stepobject_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    
        migrations.CreateModel(
            name='OrganizerSlotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('is_present', models.BooleanField(default=False)),
                ('is_empty', models.BooleanField(blank=True, help_text='None = unknown, True = empty, False = contains parts', null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
        ),
        migrations.AlterModelOptions(
            name='steprequiredcomponent',
            options={},
        ),
        migrations.RemoveField(
            model_name='bin',
            name='box_code',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='location',
        ),
        migrations.RemoveField(
            model_name='steprequiredcomponent',
            name='bin',
        ),
        migrations.AddField(
            model_name='bin',
            name='bin_code',
            field=models.CharField(
            max_length=32,
            unique=True,
            db_index=True,
            editable=False,
            null=True,
            blank=True,
            ),  # Ensure the field is nullable and blank
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steprequiredcomponent',
            name='preferred_bins',
            field=models.ManyToManyField(blank=True, related_name='preferred_for_requirements', to='api.bin'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='api.component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_code',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='steprequiredcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_in_steps', to='api.component'),
        ),
        migrations.AlterField(
            model_name='steprequiredcomponent',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_components', to='api.assemblystep'),
        ),
        migrations.AddConstraint(
            model_name='steprequiredcomponent',
            constraint=models.UniqueConstraint(fields=('step', 'component'), name='uniq_step_component_requirement'),
        ),
        migrations.AddField(
            model_name='organizerslotstate',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.bin'),
        ),
        migrations.AddField(
            model_name='organizerslotstate',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_states', to='api.organizer'),
        ),
        migrations.AddConstraint(
            model_name='organizerslotstate',
            constraint=models.UniqueConstraint(fields=('organizer', 'position'), name='uniq_position_per_organizer'),
        ),
    ]
