# Generated by Django 5.2.8 on 2025-12-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organizer_organizerslotstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_code',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True),
        ),
    ]
