# Generated by Django 5.2.8 on 2026-03-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bin_bin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerslotstate',
            name='led_section',
            field=models.PositiveIntegerField(blank=True, help_text='Physical LED/light-gate section number for this slot', null=True),
        ),
        migrations.AddConstraint(
            model_name='organizerslotstate',
            constraint=models.UniqueConstraint(fields=('organizer', 'led_section'), name='uniq_led_section_per_organizer'),
        ),
    ]
